openapi: 3.0.0
info:
  title: API de la entidad Curso
  version: 1.0.0

paths:
  /cursos:
    post:
      summary: Crear un curso nuevo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                codigo:
                  type: string
                creditos:
                  type: integer
                estado:
                  type: integer
      responses:
        '201':
          description: Curso creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  nombre:
                    type: string
                    example: Programacion II
                  codigo:
                    type: string
                    example: 220260900017B
                  creditos:
                    type: integer
                    example: 5
                  estado:
                    type: integer
                    example: 1
        '400':
          description: Datos invalidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  error:
                    type: string
                    example: Bad Request
                  message:
                    type: string
                    example: No se puede procesar la información de manera correcta.
    get:
      summary: Obtener todos los cursos creados (con filtro opcional por codigo)
      parameters:
        - name: codigo
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Lista de cursos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    nombre:
                      type: string
                      example: Programacion II
                    codigo:
                      type: string
                      example: 220260900017B
                    creditos:
                      type: integer
                      example: 5
                    estado:
                      type: integer
                      example: 1
        '404':
          description: No se encontro el curso con el codigo ingresado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  error:
                    type: string
                    example: Not found
                  message:
                    type: string
                    example: No existe el curso con el codigo ingresado.
  /cursos/{id}:
    put:
      summary: Actualizar el curso por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                codigo:
                  type: string
                creditos:
                  type: integer
                estado:
                  type: integer
      responses:
        '200':
          description: Curso actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  nombre:
                    type: string
                    example: Calculo II
                  codigo:
                    type: string
                    example: 220260900016B
                  estado:
                    type: string
                    example: 0
        '400':
          description: Datos invalidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  error:
                    type: string
                    example: Bad request.
                  message:
                    type: string
                    example: No se pudo procesar la informacion de manera correcta.
        '404':
          description: Curso no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  error:
                    type: string
                    example: Not found
                  message:
                    type: string
                    example: No existe un curso con el id ingresado.
    delete:
      summary: Eliminar curso por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Curso eliminado correctamente
        '404':
          description: Curso no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  error:
                    type: string
                    example: Not found
                  message:
                    type: string
                    example: No existe un curso con el id ingresado.
                