openapi: 3.0.0
info:
  title: API para entidad Reserva
  version: 1.0.0

paths:
  /reservas:
    post:
      summary: Crear una reserva
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservaRequest'
      responses:
        '201':
          description: Reserva creada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserva'
        '400':
          description: Datos invalidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: Obtener todas las reservas
      responses:
        '200':
          description: Lista de reservas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reserva'
  /reservas/{id}:
    get:
      summary: Obtener reserva por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Reserva encontrada con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserva'
        '404':
          description: Reserva con id ingresado no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Actualizar Reserva por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservaRequest'
      responses:
        '200':
          description: Reserva actualizada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserva'
        '400':
          description: Datos invalidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Reserva no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /reservas/{id}/cancelar:
    patch:
      summary: Cancelar una reserva
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Reserva cancelada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserva'
        '404':
          description: Reserva no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: La reserva ya estaba cancelada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ReservaRequest:
      type: object
      properties:
        nombreCliente:
          type: string
        habitacion:
          type: string
        fechaEntrada:
          type: string
          format: date
        fechaSalida:
          type: string
          format: date
        estado:
          type: integer
    
    Reserva:
      type: object
      properties:
        id:
          type: integer
        nombreCliente:
          type: string
        habitacion:
          type: string
        fechaEntrada:
          type: string
          format: date
        fechaSalida:
          type: string
          format: date
        estado:
          type: integer
    
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
        error:
          type: string
        message:
          type: string